### ISSUE TITLE
Question about using dlplus with NEC PC-8300

### ISSUE THREAD

**Issue by explit7** [bkw777/dlplus#1]
Hello Brian, i didn't found you email, so i will post it as an issue.
I have NEC PC-8300 with REX# RAM/ROM Extension and TS-DOS. All i want is to transfer file from my Linux PC to NEC PC-8300.
On my Linux PC i compiled dlplus, its working, my USB2SERIAL Adapter is on /dev/ttyUSB0, anything is fine.
But now i don't understand exactly, what tasks need to be done, so i can access the current working dlplus directory on my Linux PC as TPDD Drive from the TSDOS.

When i run dlplus without parameters - it starts with no errors, but the disk is not ready when i try to open it from TD-DOS with F4.
Should i first bootstrap a special file?

Maybe you will find couple minutes of time to explain the needed steps here?

I thank you very much

Pawel

**Comment by bkw777** [comment]
If you have TS-DOS already, as you do from REX#, then there is nothing else you need on the client side. The bootstrap function in dlplus is just a way to get TS-DOS or other client software installed, and you already have that via ROM.

"Disk not ready" usually means the serial cable isn't right. See http://tandy.wiki/Model_T_Serial_Cable for the details and links to pre-made cables that are correct.

Specifically make sure the DSR & DTR lines are connected between machines, or at least shorted to each other at each end. TS-DOS looks at DSR to determine if the drive is connected and turned on.

**Comment by explit7** [comment]
Hi Brian! Thank you for the info, i understand. As i used the same cable to forward my Linux console to the NEC PC-8300 i was quite "sure", that the cable works. will solder the new cable and try again.

Thank you very much !

**Comment by explit7** [comment]
Now anything works, i found the right Null-Modem-Cable from my PSION :) Thank you very much, you made my day!
