### ISSUE TITLE
DLPLUS on MacOS X ( M1 )

### ISSUE THREAD

**Issue by Cedric-NET** [bkw777/dlplus#4]
Hey Brian,
First of - thanks for what you're doing for the whole retro community.

Under MacOS X ( M1 in my case) running dlplus as tpdd server with no other argument than the device name, a USB-C to serial dongle in my case

Program runs fine,

However if you let it run AND remove the USB dongle, the program loops in an error, filling up the screen... And **filling up the memory**, I just killed dlplus on my mac after it taking **55 Gigabytes** (fifty five) of memory on my mac (didn't know this was even possible)

If you could look at that, probably just have the program exit when you remove the usb device and not loop forever (especially if it allocates ram at each loop)  :  that would be much appreciated

**Comment by bkw777** [comment]
Try it now.

Linux apparently doesn't notice when the tty goes away and just continues to wait for bytes no different than normal (not racing/polling, no cpu, just waiting for an even that never comes), so it wasn't a problem on linux. But macos generates an even of some sort and the read() in "while read() ..." exits, and the following code didn't handle any error condition and you got that loop. But linux never exits that read() so nothing bad happens.

It's working for me now but not an M1 just a 2015-ish air.
https://github.com/bkw777/dlplus/commit/8ab5b5bbda19a8ea69e06be36fc884abaafecf48

**Comment by bkw777** [comment]
I probably need to add that in a few other places too, so if you hit it again, I just haven't  looked around for all the other possible spots yet but it's simple. Then again read_client_tty() is used for almost all transactions, so fixing it there maybe does do almost the whole job in one shot after all.

**Comment by Cedric-NET** [comment]
Thanks - trying tonight , I’m mostly reporting this problem for the future generations :)
